Add SnowflakeIdGenerator
BeanMicro/snowflakeid pull request #1
Opened 2024-03-21 17:26 UTC by vicpham

2024-03-22 01:07 UTC, peterbean410 commented on snowflakeid/src/test/java/snowflakeid/SnowflakeIdGeneratorTest.java
> +    private static final long SEQUENCE_BITS = 12;
It is fine to use traditional tests, but BDD tests must come first

2024-03-22 01:28 UTC, peterbean410 requested changes

2024-03-22 01:28 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeIdGenerator.java
> +    public SnowflakeIdGenerator(long machineId) {
Very error-prone, if the consumer accidentally passes in the same machineId for different threads, this will break the specs.

2024-03-22 01:28 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeIdGenerator.java
> +            timestamp++;
same as `    public synchronized long nextId(Instant instant) {`

2024-03-22 01:28 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeIdGenerator.java
> +    public synchronized long nextId(Instant instant) {
`synchronized` is very inefficient in this case.
Passing `Instant` makes no sense here, why would a Java library relies on the client code to generate current timestamp ?

2024-03-22 01:28 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeIdGenerator.java
> +        sequence++;
wrong specs, sequence should be reset to 0 if it is still the same timestamp as last generation.

2024-03-22 01:28 UTC, peterbean410 commented on snowflakeid/src/test/java/snowflakeid/SnowflakeIdGeneratorTest.java
> +    })
What is the point of doing this while we already have the BDD features

2024-03-22 01:28 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeIdGenerator.java
> +    private long sequence = -1L;
not very thread-safe especially under multi processors and really heavy load

2024-03-22 12:39 UTC, peterbean410 requested changes

2024-03-22 12:39 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +    private static final long sequenceMask = ~(-1L << sequenceBits);
Let's use `SCREAMING_SNAKE_CASE` for constants.

https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

<img width="1410" alt="Screenshot 2024-03-22 at 6 51 31 PM" src="https://github.com/BeanMicro/snowflakeid/assets/76221624/5fd01900-f64a-4c29-bb14-8e0c5a547170">

2024-03-22 12:39 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +            synchronized (SnowflakeId.class) {
Totally very inefficient during warm up

2024-03-22 12:39 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +                if (instance == null) {
This could be faster

2024-03-22 12:39 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +        }
in a heavy environment, it will always move backwards if you do it like this.

2024-03-22 12:39 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +        long timestamp = timeGen();
```suggestion
        long currentTimestamp = getCurrentTimestamp();
```

2024-03-22 12:39 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +            sequence.set((sequence.get() + 1) & sequenceMask);
This is still `i = i + 1` thread safety problem.
Use this instead
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/AtomicLong.html#incrementAndGet--

2024-03-22 12:39 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +        while (timestamp <= lastTimestamp) {
This will loop for a very very very long time in a heavy multi-thread environment.

2024-03-22 12:39 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +    private long machineId = getMachineId();
What is the point of singleton instance when we init everything on ClassLoading

2024-03-22 12:39 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +            return Math.abs(hashBytes[0]);
So many unnecessary operations, we only need to `combinedString.hashCode() / MachineBitNumber`

2024-03-22 12:39 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +    private static final long sequenceBits = 12L;
It's a waste of memory here and below.

2024-03-30 07:58 UTC, vicpham commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +            synchronized (SnowflakeId.class) {
https://en.wikipedia.org/wiki/Double-checked_locking#Usage_in_Java

2024-03-30 10:09 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +    private static final int SEQUENCE_MASK = ~(-1 << SEQUENCE_BITS);
```suggestion
    private static final short MACHINE_ID_BITS = 10;
    private static final short SEQUENCE_BITS = 12;
    private static final short MAX_MACHINE_ID = ~(-1 << MACHINE_ID_BITS);
    private static final short MACHINE_ID_SHIFT = SEQUENCE_BITS;
    private static final short TIMESTAMP_LEFT_SHIFT = SEQUENCE_BITS + MACHINE_ID_BITS;
    private static final short SEQUENCE_MASK = ~(-1 << SEQUENCE_BITS);
```

2024-03-30 10:10 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +        this.epoch = epoch;
Why don't you check `NULL` and set the right epoch here, then there s no need to keep checking for `NULL` later.

2024-03-30 10:11 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +            synchronized (SnowflakeId.class) {
@vicpham please research carefully how to efficiently implement Singleton without `synchronize` keyword

2024-03-30 10:13 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +    }
MachineID is only calculated once, why not do it inside getInstance ???

2024-03-30 10:20 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +            synchronized (SnowflakeId.class) {
![Uploading Screenshot 2024-03-30 at 5.20.20 PM.png…]()

2024-03-30 10:20 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +            synchronized (SnowflakeId.class) {
<img width="965" alt="Screenshot 2024-03-30 at 5 20 48 PM" src="https://github.com/BeanMicro/snowflakeid/assets/76221624/b42d87a7-675c-4648-ab5b-6922448b8fb2">

2024-03-30 10:27 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +        long lastDelta = lastTsBasedSequence.get() >> SEQUENCE_BITS;
```suggestion
        long lastDelta = lastTsBasedSequence.get() >> SEQUENCE_BITS;
        long now = getCurrentTimestamp();
        long delta = now - epoch;
```

lastDelta has be to extracted BEFORE now

2024-03-30 10:42 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +        return Instant.now(clock).toEpochMilli();
```suggestion
        return Instant.now(clock).toEpochMilli() - epoch;
```

as explained above

2024-03-30 10:53 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +        }
```suggestion
        if (lastTimestamp == currentTimestamp) {
            curr = lastTsBasedSequence.incrementAndGet();
        } else {
            curr = lastTsBasedSequence.accumulateAndGet(currentTimestamp << SEQUENCE_BITS, (p, c) -> {
            // if lastTimestamp (p) is still less than currentTimestamp (c)
            //       return c
            //  return p + 1
            });
        }
```

2024-04-01 05:21 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +                curr & SEQUENCE_MASK;
Small issue here, there is no guarantee that the now ts fetched earlier is the most up to date timestamp. So, we should re-calculate the latest timestamp from `curr`

2024-04-01 05:23 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +            if (lastTimestamp < currentTimestamp) {
```suggestion
            if (p < c) {
```

2024-04-01 05:24 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +            if (p < c) {
```suggestion
            if (p < c) { // To make sure that the current timestamp is still a more recent value
```

2024-04-01 05:26 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +    }
This is still not enough, the first check "before lambda" is different from the check "inside lambda"

2024-04-01 05:28 UTC, peterbean410 commented on snowflakeid/src/main/java/snowflakeid/SnowflakeId.java
> +    long updateLastTimestampBasedSequenceAndGet(long lastTimestamp, long currentTimestamp) {
```suggestion
    long updateLastTimestampBasedSequenceAndGet(long lastTimestamp, long currentTimestamp) {
    // if lastTimestamp == currentTimestamp
    //      return lastTsBasedSequence.incrementAndGet();
    // end if
```

2024-04-01 17:17 UTC, peterbean410 approved these changes

2024-04-01 17:18 UTC, merged